### ISSUE TITLE
Update Presentations

### ISSUE THREAD

**Issue by pasindud** [CMBJS/Meetups#2]
@iamchathu  can you add the presentations for meetups
- Data layers of modern JavaScript apps
- JS in Mobile App Development

**Comment by iamchathu** [comment]
@pasindud

https://github.com/CMBJS/Meetups/tree/master/March%20-%202016 JS in mobile App developement

**Comment by iamchathu** [comment]
@pasindud 

https://github.com/CMBJS/Meetups/tree/master/Dec%20-%202015 Data layers of modern JS Apps

**Comment by pasindud** [comment]
Thanks
